spring.datasource.url=${MYWAY_DB_URL}
spring.datasource.username=${MYWAY_DB_USERNAME}
spring.datasource.password=${MYWAY_DB_PASSWORD}
spring.sql.init.mode=always

myway.app.env=production
myway.runtime.env=production
