import type { CourseCard, LectureDetail, LoginResponse } from '@myway/shared';
import { StatePanel } from '../components/StatePanel';

export function formatStudyHours(totalMinutes: number) {
  if (totalMinutes <= 0) return '0시간';
  return `${Math.round(totalMinutes / 60)}시간`;
}

export function getPopularKeywords(courses: CourseCard[]) {
  const keywords = courses.flatMap((course) => [course.category, ...(Array.isArray(course.tags) ? course.tags : [])]);
  return [...new Set(keywords)].filter(Boolean).slice(0, 6);
}

export function courseVisualClasses(palette: CourseCard['thumbnail_palette']) {
  if (palette === 'emerald') return 'from-emerald-900 via-emerald-700 to-teal-500';
  if (palette === 'violet') return 'from-violet-950 via-purple-700 to-fuchsia-500';
  if (palette === 'amber') return 'from-amber-950 via-amber-700 to-orange-400';
  return 'from-blue-950 via-cyan-800 to-sky-500';
}

export function HomeHero({ session, averageProgress, enrolledCourses, onNavigate }: { session: LoginResponse; averageProgress: number; enrolledCourses: number; onNavigate: (page: 'home' | 'dashboard' | 'courses' | 'shortform' | 'community' | 'my-shortforms' | 'ai-chat') => void }) {
  return <section className="relative overflow-hidden rounded-[26px] border border-cyan-200/35 bg-[radial-gradient(circle_at_15%_10%,rgba(34,211,238,0.28),transparent_32%),radial-gradient(circle_at_75%_30%,rgba(14,116,144,0.45),transparent_45%),linear-gradient(120deg,#031d3a_0%,#05345f_55%,#0a4168_100%)] p-6 text-white shadow-[0_20px_60px_rgba(8,47,73,0.45)] lg:p-8"><div className="pointer-events-none absolute -right-16 top-10 h-64 w-64 rounded-full border border-cyan-300/30" /><div className="pointer-events-none absolute right-16 top-24 h-44 w-44 rounded-full border border-cyan-300/15" /><div className="pointer-events-none absolute bottom-8 right-10 h-20 w-20 rounded-2xl border border-cyan-200/25 bg-cyan-300/10 backdrop-blur" /><div className="relative z-10 grid items-center gap-8 lg:grid-cols-[minmax(0,1.1fr)_minmax(260px,0.9fr)]"><div><span className="inline-flex rounded-full border border-cyan-200/40 bg-white/10 px-3 py-1 text-[11px] font-semibold tracking-[0.03em] text-cyan-100">AI Learning Home · {session.user.name}</span><h2 className="mt-5 text-[34px] font-extrabold leading-[1.2] tracking-[-0.03em] text-white lg:text-[46px]">AI로 배우고,<br />성장하는 실력</h2><p className="mt-4 max-w-xl text-[15px] leading-7 text-cyan-50/90">2026년, 학습부터 실전까지 이어지는 개인 맞춤형 러닝 허브. 강의 탐색부터 AI 질문, 숏폼 복습까지 한 흐름으로 시작하세요.</p><div className="mt-6 flex flex-wrap gap-3"><button type="button" onClick={() => onNavigate('courses')} className="rounded-xl bg-cyan-300 px-5 py-2.5 text-[13px] font-bold text-cyan-950 transition hover:bg-cyan-200">강의 탐색 시작</button><button type="button" onClick={() => onNavigate('ai-chat')} className="rounded-xl border border-cyan-100/30 bg-white/10 px-5 py-2.5 text-[13px] font-semibold text-cyan-50 backdrop-blur transition hover:bg-white/20">AI 도우미 열기</button></div></div><div className="relative mx-auto w-full max-w-[360px]"><div className="absolute inset-0 rounded-[28px] bg-cyan-300/15 blur-2xl" /><div className="relative rounded-[28px] border border-cyan-100/25 bg-white/10 p-6 backdrop-blur"><div className="mx-auto flex h-28 w-28 items-center justify-center rounded-[26px] border border-cyan-200/35 bg-gradient-to-br from-cyan-200/95 to-cyan-400/70 text-[48px] font-black text-slate-900 shadow-[0_20px_40px_rgba(34,211,238,0.35)]">AI</div><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-2xl border border-cyan-100/20 bg-slate-950/35 px-3 py-2"><div className="text-[11px] text-cyan-100/80">진행률</div><div className="mt-1 text-[18px] font-extrabold text-cyan-100">{averageProgress}%</div></div><div className="rounded-2xl border border-cyan-100/20 bg-slate-950/35 px-3 py-2"><div className="text-[11px] text-cyan-100/80">수강 강의</div><div className="mt-1 text-[18px] font-extrabold text-cyan-100">{enrolledCourses}개</div></div></div></div></div></div></section>;
}

export function ContinueStudySection({ highlightedLecture, continueCourse, onSelectCourse, onNavigate }: { highlightedLecture: LectureDetail | null; continueCourse: CourseCard | null; onSelectCourse: (courseId: string) => void; onNavigate: (page: 'home' | 'dashboard' | 'courses' | 'shortform' | 'community' | 'my-shortforms' | 'ai-chat') => void }) {
  return <section className="rounded-2xl border border-slate-200 bg-white px-5 py-5 shadow-sm"><div><div className="flex items-center justify-between"><h3 className="text-[16px] font-bold text-slate-900">지금 이어볼 강의</h3><span className="rounded-full bg-slate-100 px-3 py-1 text-[11px] font-semibold text-slate-600">학습 재개</span></div>{highlightedLecture && continueCourse ? <div className="mt-4 rounded-2xl border border-slate-200 bg-slate-50 px-5 py-5"><div className="text-[11px] font-semibold text-cyan-700">CONTINUE</div><div className="mt-2 text-[20px] font-bold tracking-[-0.02em] text-slate-900">{highlightedLecture.title}</div><div className="mt-1 text-[13px] text-slate-500">{highlightedLecture.course_title} · {highlightedLecture.course_instructor}</div><div className="mt-4 h-2 overflow-hidden rounded-full bg-white"><div className="h-full rounded-full bg-cyan-500" style={{ width: `${Math.max(continueCourse.progress_percent, 8)}%` }} /></div><div className="mt-2 text-[12px] text-slate-500">{continueCourse.completed_lectures}/{continueCourse.lecture_count}차시 완료 · {continueCourse.progress_percent}% 진행</div><div className="mt-5 flex flex-wrap gap-2"><button type="button" onClick={() => { onSelectCourse(highlightedLecture.course_id); onNavigate('courses'); }} className="rounded-lg bg-cyan-600 px-4 py-2 text-[12px] font-semibold text-white transition hover:bg-cyan-500">강의로 이동</button><button type="button" onClick={() => onNavigate('shortform')} className="rounded-lg border border-slate-200 bg-white px-4 py-2 text-[12px] font-semibold text-slate-700 transition hover:border-cyan-300 hover:text-cyan-700">숏폼 복습</button></div></div> : <div className="mt-4"><StatePanel compact icon="ri-play-circle-line" tone="indigo" title="이어볼 강의가 없습니다." description="수강 중인 강의가 생기면 홈에서 바로 이어서 학습할 수 있습니다." /></div>}</div></section>;
}
